# Use official Python image
FROM python:3.9-slim

# Set working directory inside container
WORKDIR /app

# Copy all files to container
COPY . /app

# Install dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Default command
CMD ["python", "src/app.py"]
